---
title: "Current Teaching"
author: "Corey Sparks, PhD"
date: "7/22/2020"
output: html_document
---

Here are the courses I teach in our [program in Applied Demography.](https://hcap.utsa.edu/demography/programs/)

While at UTSA, I have had the opportunity to develop effective and current courses. My teaching while in the Department of Demography has focused on two main areas; advanced quantitative methods and spatial analysis.  

I have designed courses in introductory statistics, hierarchical models and hazards analysis, in addition to two courses in Geographic Information Systems and spatial statistics. 

In general, my philosophy towards instruction is to provide students with up to date instruction on methods that are currently being employed by professionals in the diverse field of demography, and provide an arena for them to gain experience using these methods on practical and realistic examples. 

The courses I teach stress the application of the R programming language and the use of the Linux environment.  I encourage hands on usage of computers, along with modern data visualization methods to enhance the learning of students, and I believe based on discussions with colleagues at other institutions, that the curriculum represents a unique graduate educational experience. 

## Syllabi
All of my current syllabi can be found the [UTSA Bluebook page.](https://bluebook.utsa.edu)

## Current Courses
My current course examples can be seen at [my Rpubs page](https://rpubs.com/corey_sparks) at at my [Github repository](github.com/coreysparks)

Demog [7223 Advanced methods for life table analysis](github.com/coreysparks/DEM7223)
Demog [7283 Statistical Methods for Demographic Data 2](github.com/coreysparks/DEM7283)
Demog 7263 Spatial Demography 
Demog 7093 GIS for Population Science 
Demog 7273 Statistical Methods for Demographic Data 1
Demog 7473 Applied Hierarchical Modeling